name: Docker Image CI

on:
  push:
    branches:
    - master    

jobs:
  build:
    env:
      imageTag: $(date +%s)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stitchmoney/chrome-headless-for-puppeteer:$imageTag
    - name: Login to container registry
      run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Image
      run: docker push stitchmoney/chrome-headless-for-puppeteer:$imageTag


